---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@e446e8a4a08b3a5e031c5d1f92ed3af8a1b90063 # 1.12.0
    secrets: inherit
