---
name: Check spelling

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@75d49c94ed8b9ac8826afbfcc1cca87b0e73deb8 # 1.11.0
    secrets: inherit
