---
name: Check spelling

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@221368ae36e54bb78fbacbb1745d3a8658220f93 # 1.10.2
    secrets: inherit
