---
name: Close stale issues and PRs

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@9b2ba281669d7d3bb2e609a83fee46bee24aa6e8 # 1.10.0
    secrets: inherit
