---
name: Close stale issues and PRs

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@42d5823deada64f84e11ff904dd542e9fbb10ffa # 1.7.1
    secrets: inherit
